version: '3.1'
services:
    mysql:
        container_name: mysql
        image: 'mysql:8.0'
        command: mysqld --default-authentication-plugin=mysql_native_password
        working_dir: /application
        volumes:
            - './src:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=ssp
            - MYSQL_USER=ssp
            - MYSQL_PASSWORD=password
        ports:
            - '3306:3306'

    webserver:
        container_name: webserver
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './src:/application:cached'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        tty: true

    php-fpm:
        container_name: php-fpm
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - ./src/api:/application:cached
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
            - /src/api/vendor
        links:
            - cache

    cache:
        container_name: cache
        image: redis:alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass password
        volumes:
            - ./cache:/data

    angular:
        container_name: angular
        build: src/angular
        working_dir: /application
        volumes:
            - './src/angular:/application'
        ports: 
            - '4200:4200'
        command: ng serve --host 0.0.0.0 --poll=2000
    caddy:
        container_name: mercure
        image: dunglas/mercure
        environment:
          DEBUG: "debug"
          SERVER_NAME: ':80'
          MERCURE_PUBLISHER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.iHLdpAEjX4BqCsHJEegxRmO-Y6sMxXwNATrQyRNt3GY'
          MERCURE_SUBSCRIBER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.iHLdpAEjX4BqCsHJEegxRmO-Y6sMxXwNATrQyRNt3GY'
          MERCURE_EXTRA_DIRECTIVES: |-
            cors_origins "*"
            anonymous
        ports:
          - "1337:80"